workflows:
  bluid:
    name: Build App
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk
      - name: Analyce code
        script: |
          flutter analyze
      - name: Run tests
        script: |
          flutter test
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - effrenanthony2704@gmail.com
        notify:
          success: true
          failure: true